version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment: 
      MYSQL_DATABASE: forum
      MYSQL_USER: forum_user
      MYSQL_PASSWORD: forum_pass
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: forum-backend
    command: python forum/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data: