services:
  db:
    image: mysql:8
    restart: always
    environment: 
      MYSQL_DATABASE: forum
      MYSQL_USER: forum_user
      MYSQL_PASSWORD: forum_pass
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: forum-backend
    command: python forum/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app/forum
    env_file:
      - .env

  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-daphne
    command: daphne -b 0.0.0.0 -p 8001 forum.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app/forum
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    container_name: forum-celery
    working_dir: /app/forum
    command: celery -A forum worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app/forum
    env_file:
      - .env

volumes:
  mysql_data: