# Generated by Django 5.2 on 2025-04-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_thread',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
