# Generated by Django 5.2 on 2025-04-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_rename_uploaded_at_attachments_created_at'),
        ('comments', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comments.comment'),
        ),
    ]
