# Generated by Django 5.2 on 2025-04-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_alter_attachments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('text', 'Text file')], max_length=10),
        ),
    ]
