# Generated by Django 5.0.1 on 2025-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_alter_attachments_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
